import React from 'react';
import { Button } from '../ui/Button';
import { Badge } from '../ui/Badge';
import { X, Printer, Cpu, ShieldCheck } from 'lucide-react';
import type { RecommendationResponse, ShipmentPayload } from '../../types';
import { formatCurrency, formatPercent } from '../../lib/utils';

interface ReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  result: RecommendationResponse;
  payload: ShipmentPayload;
}

export const ReportModal: React.FC<ReportModalProps> = ({
  isOpen,
  onClose,
  result,
  payload,
}) => {
  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 bg-slate-950/85 backdrop-blur-md z-50 flex items-center justify-center p-4 overflow-y-auto animate-fadeIn">
      <div className="max-w-3xl w-full bg-slate-900 border border-slate-700 rounded-2xl p-8 space-y-6 shadow-2xl text-slate-100 relative">
        {/* Header Actions */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-800">
          <div className="flex items-center gap-3">
            <div className="p-2.5 bg-indigo-600 text-white rounded-xl">
              <Cpu className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-xl font-extrabold text-white">Executive AI Decision Report</h2>
              <p className="text-xs text-slate-400">Generated by ChainIQ CatBoost Classifier v1.5</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" leftIcon={<Printer className="w-3.5 h-3.5" />} onClick={handlePrint}>
              Print / Save PDF
            </Button>
            <button onClick={onClose} className="p-2 text-slate-400 hover:text-white rounded-lg">
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Report Content Body */}
        <div className="space-y-6 text-xs">
          {/* Order & Prediction Header */}
          <div className="grid grid-cols-2 gap-4 p-4 rounded-xl bg-slate-950 border border-slate-800">
            <div>
              <span className="text-slate-400 font-medium">Market / Mode:</span>
              <p className="font-bold text-white text-sm">{payload.Market} • {payload.Shipping_Mode}</p>
              <p className="text-slate-400 mt-1">Total Sales: <strong className="text-white">{formatCurrency(payload.Sales)}</strong></p>
            </div>
            <div className="text-right">
              <span className="text-slate-400 font-medium">Predicted Risk:</span>
              <p className="text-xl font-extrabold text-rose-400">{formatPercent(result.prediction.delay_probability)} ({result.prediction.risk_level})</p>
              <p className="text-emerald-400 font-semibold mt-1">Model Confidence: {result.prediction.confidence}%</p>
            </div>
          </div>

          {/* Root Causes */}
          <div className="space-y-2">
            <h4 className="font-bold text-white uppercase text-[11px]">Identified Root Cause Indicators</h4>
            <div className="flex flex-wrap gap-2">
              {result.possible_causes.map((c, i) => (
                <span key={i} className="px-2.5 py-1 rounded bg-amber-500/20 text-amber-300 border border-amber-500/30">
                  {c}
                </span>
              ))}
            </div>
          </div>

          {/* Recommended Interventions */}
          <div className="space-y-2">
            <h4 className="font-bold text-white uppercase text-[11px]">Prescribed Interventions</h4>
            <div className="space-y-1.5">
              {result.recommendations.map((r, i) => (
                <div key={i} className="p-2.5 rounded bg-slate-950 border border-slate-800 flex justify-between items-center">
                  <span className="text-slate-200 font-medium">{r.action}</span>
                  <Badge variant="indigo" size="sm">{r.priority} Priority</Badge>
                </div>
              ))}
            </div>
          </div>

          {/* Business Impact */}
          <div className="p-4 rounded-xl bg-emerald-950/20 border border-emerald-500/30 flex items-center justify-between">
            <div>
              <span className="text-slate-400">Estimated Cost Saving:</span>
              <p className="text-lg font-bold text-emerald-400">{formatCurrency(result.business_impact.estimated_cost_saving_usd)}</p>
            </div>
            <div className="text-right">
              <span className="text-slate-400">Delay Reduction:</span>
              <p className="text-lg font-bold text-cyan-400">{result.business_impact.estimated_delay_reduction_days} Days</p>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="pt-4 border-t border-slate-800 flex items-center justify-between text-[11px] text-slate-500">
          <span>Report ID: CHNQ-RPT-{Date.now().toString().slice(-6)}</span>
          <span className="flex items-center gap-1"><ShieldCheck className="w-3.5 h-3.5 text-emerald-400" /> Authenticated Intelligence Output</span>
        </div>
      </div>
    </div>
  );
};
